curl -X PUT "localhost:9200/_index_template/template_flows?pretty" -H 'Content-Type: application/json' -d @flows.json
curl -X PUT "localhost:9200/_index_template/template_apt_dns?pretty" -H 'Content-Type: application/json' -d @apt_dns.json
curl -X PUT "localhost:9200/_index_template/template_bars_victims?pretty" -H 'Content-Type: application/json' -d @bars_victims.json
curl -X PUT "localhost:9200/_index_template/template_x509?pretty" -H 'Content-Type: application/json' -d @x509.json
curl -X PUT "localhost:9200/_index_template/template_nmap_dnsrr?pretty" -H 'Content-Type: application/json' -d @nmap_dnsrr.json
curl -X PUT "localhost:9200/_index_template/template_useragents?pretty" -H 'Content-Type: application/json' -d @useragents.json
curl -X PUT "localhost:9200/_index_template/template_open_ports?pretty" -H 'Content-Type: application/json' -d @open_ports.json
curl -X PUT "localhost:9200/_index_template/template_nmap_port?pretty" -H 'Content-Type: application/json' -d @nmap_port.json
curl -X PUT "localhost:9200/_index_template/template_urls?pretty" -H 'Content-Type: application/json' -d @urls.json
curl -X PUT "localhost:9200/_index_template/template_bars_controllers?pretty" -H 'Content-Type: application/json' -d @bars_controllers.json
curl -X PUT "localhost:9200/_index_template/template_os_fingerprint?pretty" -H 'Content-Type: application/json' -d @os_fingerprint.json
curl -X PUT "localhost:9200/_index_template/template_beacons?pretty" -H 'Content-Type: application/json' -d @beacons.json
curl -X PUT "localhost:9200/_index_template/template_nmap_fingerprint?pretty" -H 'Content-Type: application/json' -d @nmap_fingerprint.json
curl -X PUT "localhost:9200/_index_template/template_compromised_hosts?pretty" -H 'Content-Type: application/json' -d @compromised_hosts.json
curl -X PUT "localhost:9200/_index_template/template_ssh?pretty" -H 'Content-Type: application/json' -d @ssh.json
curl -X PUT "localhost:9200/_index_template/template_banners?pretty" -H 'Content-Type: application/json' -d @banners.json
curl -X PUT "localhost:9200/_index_template/template_banners_ptr?pretty" -H 'Content-Type: application/json' -d @banners_ptr.json
curl -X PUT "localhost:9200/_index_template/template_pdns?pretty" -H 'Content-Type: application/json' -d @pdns.json
curl -X PUT "localhost:9200/_index_template/template_scanner?pretty" -H 'Content-Type: application/json' -d @scanner.json
curl -X PUT "localhost:9200/_index_template/template_darknet?pretty" -H 'Content-Type: application/json' -d @darknet.json
curl -X PUT "localhost:9200/_index_template/template_cookies?pretty" -H 'Content-Type: application/json' -d @cookies.json
