filebeat.config.inputs:
  enabled: true
  path: inputs.yml
  reload.enabled: true
  reload.period: 20s
# filebeat.inputs:
  

output.logstash:
  hosts: ["logstash:5044"]

processors:
  - drop_fields:
      fields: [ "agent", "log", "ecs", "tags", "host", "input" ]
